---
SSH_PASSWORD: "password"
SSH_USERNAMES:
  - username: "user1"
    ip: "192.168.1.1"
  - username: "user2"
    ip: "192.168.1.2"
  - username: "user3"
    ip: "192.168.1.3"
BLACKBOX_PATH: "logs/blackbox.csv"
LOCAL_PATH: "."
