---
SSH_PASSWORD_CORAL: ""
SSH_PASSWORD_PI: ""
SSH_PASSWORD: "" #for testing
BLACKBOX_PATH: "~/blackboxV10RM1/" #for testing
BLACKBOX_PATH_PI: "~/Sensor/logs/blackbox.csv"
BLACKBOX_PATH_CORAL: "/mnt/storage/logs"
LOCAL_PATH: "./blackboxes"
